class ProfileModel {
  final String userId;
  final String lgnId;
  final String userNm;
  final String pwd;
  final String emilAddr;
  final String gndrCd;
  final String age;
  final String sttr;
  final String bdwg;
  final String hateFood;
  final String likeFood;
  final String wklyBestActvDycnt;
  final String dyBestActvHr;
  final String dyBestActvMin;
  final String wklyMddlActvDycnt;
  final String dyMddlActvHr;
  final String dyMddlActvMin;
  final String workingDay;
  final String workingHour;
  final String workingMin;
  final String allergyInfo;

  ProfileModel.fromJson(Map<dynamic, dynamic> json)
      : userId = json['user_id'],
        lgnId = json['lgn_id'],
        userNm = json['user_nm'],
        pwd = json['pwd'],
        emilAddr = json['emil_addr'],
        gndrCd = json['gndr_cd'],
        age = json['age'],
        sttr = json['sttr'],
        bdwg = json['bdwg'],
        hateFood = json['hate_food'],
        likeFood = json['like_food'],
        wklyBestActvDycnt = json['wkly_best_actv_dycnt'],
        dyBestActvHr = json['dy_best_actv_hr'],
        dyBestActvMin = json['dy_best_actv_min'],
        wklyMddlActvDycnt = json['wkly_mddl_actv_dycnt'],
        dyMddlActvHr = json['dy_mddl_actv_hr'],
        dyMddlActvMin = json['dy_mddl_actv_min'],
        workingDay = json['working_day'],
        workingHour = json['working_hour'],
        workingMin = json['working_min'],
        allergyInfo = json['allergy_info'];
}
